name: Clippy check

on: push

jobs:
  cargo_doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Ensures the repo is cloned properly

      - name: Debug - List Files
        run: ls -la # Check if Cargo.toml exists

      - name: Run Cargo Doc Check
        uses: unk1ndled/rs-doc-check@v1.0.0
        with:
          args: --all-features
